services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: npm
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "80:80"     # Cổng Web
      - "443:443"   # Cổng HTTPS
      - "81:81"     # Cổng Admin
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - homelab   # Quan trọng: Phải đứng trong mạng này

networks:
  homelab:
    external: true